# Generated by Django 2.0.3 on 2018-03-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietGoalMealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'diet_goal_meal_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DietGoalMealPlanDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'diet_goal_meal_plan_dish',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=255)),
            ],
            options={
                'db_table': 'goal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=255)),
            ],
            options={
                'db_table': 'meal_plan',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='addon',
            options={'managed': False, 'verbose_name_plural': 'Add ons'},
        ),
        migrations.AlterModelOptions(
            name='allergens',
            options={'managed': False, 'verbose_name_plural': 'Allergens'},
        ),
        migrations.AlterModelOptions(
            name='calorieformulae',
            options={'managed': False, 'verbose_name_plural': 'Calorie Formulae'},
        ),
        migrations.AlterModelOptions(
            name='completedorders',
            options={'managed': False, 'verbose_name_plural': 'Completed Orders'},
        ),
        migrations.AlterModelOptions(
            name='coupons',
            options={'managed': False, 'verbose_name_plural': 'Coupons'},
        ),
        migrations.AlterModelOptions(
            name='deliveryaddress',
            options={'managed': False, 'verbose_name_plural': 'Delivery Addressess'},
        ),
        migrations.AlterModelOptions(
            name='deliveryzones',
            options={'managed': False, 'verbose_name_plural': 'Delivery zones'},
        ),
        migrations.AlterModelOptions(
            name='dietplan',
            options={'managed': False, 'verbose_name_plural': 'Diet Plans'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'managed': False, 'verbose_name_plural': 'Dishes'},
        ),
        migrations.AlterModelOptions(
            name='dishallergens',
            options={'managed': False, 'verbose_name_plural': 'Dish-Allergens'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': False, 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='holidays',
            options={'managed': False, 'verbose_name_plural': 'Holidays'},
        ),
        migrations.AlterModelOptions(
            name='mealprefchange',
            options={'managed': False, 'verbose_name_plural': 'Meal Preference Change of users'},
        ),
        migrations.AlterModelOptions(
            name='measurements',
            options={'managed': False, 'verbose_name_plural': 'Measurements'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'managed': False, 'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'managed': False, 'verbose_name_plural': 'Payments recorded'},
        ),
        migrations.AlterModelOptions(
            name='pricing',
            options={'managed': False, 'verbose_name_plural': 'Pricing'},
        ),
        migrations.AlterModelOptions(
            name='skipmeal',
            options={'managed': False, 'verbose_name_plural': 'Skip Meal'},
        ),
        migrations.AlterModelOptions(
            name='upgradeplan',
            options={'managed': False, 'verbose_name_plural': 'Updgrade plans of users'},
        ),
        migrations.AlterModelOptions(
            name='userallergens',
            options={'managed': False, 'verbose_name_plural': 'Allergens of users'},
        ),
        migrations.AlterModelOptions(
            name='userfoodpref',
            options={'managed': False, 'verbose_name_plural': 'User food preferences'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': False, 'verbose_name_plural': 'Users Profile'},
        ),
    ]
