# Generated by Django 2.0.3 on 2018-03-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20180322_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_time', models.TimeField(blank=True, null=True)),
                ('evening_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WalletConstraints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_amount', models.IntegerField(blank=True, null=True)),
                ('percentage', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wallet_constraints',
                'managed': False,
            },
        ),
    ]
