# Generated by Django 2.0.3 on 2018-03-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_ordertime_walletconstraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('replace', models.CharField(blank=True, max_length=10, null=True)),
                ('meal_time', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='Morning', max_length=255)),
            ],
            options={
                'db_table': 'add_on_orders',
                'managed': False,
            },
        ),
    ]
