# Generated by Django 2.0.3 on 2018-03-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_addonorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('num_days', models.IntegerField(blank=True, null=True)),
                ('bft', models.IntegerField(blank=True, null=True)),
                ('lnch', models.IntegerField(blank=True, null=True)),
                ('snk', models.IntegerField(blank=True, null=True)),
                ('dnr', models.IntegerField(blank=True, null=True)),
                ('new_plan_status', models.CharField(choices=[('Started', 'Started'), ('Not started', 'Not started')], default='Not started', max_length=10)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Due', 'Due'), ('Partially Paid', 'Partially Paid')], default='Due', max_length=10)),
                ('due_amount', models.IntegerField(blank=True, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'new_plan',
                'managed': False,
            },
        ),
    ]
