# Generated by Django 2.0.3 on 2018-03-26 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_newplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'managed': True, 'verbose_name_plural': 'Dishes'},
        ),
    ]
