# Generated by Django 2.0.3 on 2018-03-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20180326_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('met', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'activity_factor',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField(blank=True, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'exercise',
            },
        ),
        migrations.AlterField(
            model_name='dish',
            name='type',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian'), ('Eggetarian', 'Eggetarian')], default='Vegetarian', max_length=255),
        ),
    ]
