# Generated by Django 2.0.3 on 2018-03-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20180327_1820'),
    ]

    operations = [
    ]
