# Generated by Django 2.0.3 on 2018-03-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20180327_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'managed': False, 'verbose_name_plural': 'Dishes'},
        ),
    ]
