# Generated by Django 2.0.3 on 2018-04-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_deliverytime'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
            ],
            options={
                'managed': True,
                'db_table': 'start_date',
            },
        ),
    ]
