# Generated by Django 2.0.3 on 2018-04-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_upgardeplanpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferalConstraints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee', models.IntegerField()),
                ('referer', models.IntegerField()),
            ],
            options={
                'db_table': 'referal_constraints',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='activityfactor',
            options={'managed': True},
        ),
    ]
