# Generated by Django 2.0.3 on 2018-04-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20180413_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityfactor',
            name='activity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
