# Generated by Django 2.0.3 on 2018-04-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_auto_20180413_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryaddress',
            options={'managed': True, 'verbose_name_plural': 'Delivery Addressess'},
        ),
    ]
