# Generated by Django 2.0.3 on 2018-04-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_auto_20180413_1554'),
    ]

    operations = [
    ]
