# Generated by Django 2.0.3 on 2018-04-13 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_auto_20180413_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergens',
            options={'managed': False, 'verbose_name_plural': 'Allergens'},
        ),
    ]
