# Generated by Django 2.0.3 on 2018-04-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_auto_20180413_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordertime',
            options={'managed': True},
        ),
    ]
