# Generated by Django 2.0.3 on 2018-04-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_auto_20180413_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertime',
            name='evening_day',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='ordertime',
            name='morning_day',
            field=models.IntegerField(default=-1),
        ),
    ]
